### PR TITLE
Feature/storybook

### PR DESCRIPTION
**Pull request by csmartinsfct**

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
@csmartinsfct could you add also the `build-storybook` task so we generate the static files for the storybook?

**Comment by csmartinsfct** [comment]
Done!

**Comment by jjperezaguinaga** [comment]
@csmartinsfct sadly it's not working. I would recommend you the following to give it a try:

1. Clone repository
2. Do `npm install`
3. Do `npm run build-storybook`
4. See what are the contents of `public`

Seems like the storybook isn't being build. What could be the issue?

**Comment by csmartinsfct** [comment]
I've changed the build-storybook script so it outputs the required files to a folder.

**Comment by jjperezaguinaga** [comment]
Looking great! https://dapp-mybit-storybook-hnmidscobp.now.sh/
Awesome work!

**Pull request merged**
